service: pyblog

frameworkVersion: ">= 1.6.0 <2.0.0"

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: eu-central-1
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:Query
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:eu-central-1:186706155491:table/BlogTable"

functions:
  create:
    handler: create.handler
    events:
      - http:
          path: articles
          method: post
#  read:
#    handler: articles/read.handler
#    events:
#      - http:
#          path: articles
#          method: get
#  update:
#    handler: articles/update.handler
#    events:
#      - http:
#          path: articles
#          method: put
#  delete:
#    handler: articles/delete.handler
#    events:
#      - http:
#          path: articles
#          method: delete

resources:
  Resources:
    BlogTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PyBlogTable
        AttributeDefinitions:
          - AttributeName: article_id
            AttributeType: S
        KeySchema:
          - AttributeName: article_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
